# Generated by Django 6.0 on 2025-12-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminbloguser',
            options={'permissions': [('can_edit_any_post', 'Can edit any blog post'), ('can_delete_any_post', 'Can delete any blog post'), ('can_manage_users', 'Can manage user accounts'), ('can_make_announcements', 'Can make announcements'), ('can_edit_announcemnts', 'Can edit announcements'), ('can_delete_announcements', 'Can delete announcements')]},
        ),
        migrations.AlterModelOptions(
            name='bloguser',
            options={'permissions': [('can_create_post', 'Can create blog posts')]},
        ),
        migrations.AlterModelOptions(
            name='regularbloguser',
            options={'permissions': [('can_create_posts', 'Can create blog posts'), ('can_edit_own_post', 'Can edit own blog posts'), ('can_delete_own_post', 'Can delete own blog posts')]},
        ),
    ]
